### ISSUE TITLE
Module declaration shows "file not found"

### ISSUE THREAD

**Issue by BobTP** [jhasse/sublime-rust#36]
When defining a module in a lib.rs or mod.rs file, the module name is always highlighted red. The corresponding error message is "Error: file not found for module `xxx`" with `xxx` beeing the name of the module. However, compiling and executing works just fine.

**Comment by jhasse** [comment]
When and where do you get that error mesaage?

**Comment by BobTP** [comment]
Whenever a new module is added in a mod.rs or lib.rs. You can take a look at the sources here: https://github.com/Rubigo-Frigus/ProjectAntiG/tree/silver

**Comment by jhasse** [comment]
Can you post a screenshot? I don't quite understand where that message shows up.

**Comment by BobTP** [comment]
There you go. As you can see, vector is marked red and an error is shown in the bottom line, although vector.rs is there, as you can see from the filetree.

![screenshot from 2015-02-05 20 11 03](https://cloud.githubusercontent.com/assets/4622438/6067214/2962c8cc-ad73-11e4-913e-ea2c0663d928.png)

**Comment by jhasse** [comment]
Thanks! Sorry I didn't get it right away ;)

The error message actually comes from a different package: SublimeLinter using the rust plugin. You'll need to configure it to use cargo or the crate root for it to find other modules: https://github.com/oschwald/SublimeLinter-contrib-rustc#settings

**Comment by BobTP** [comment]
Ok, thank you. Sorry I didn't recognize it was not the fault of your project.
