### ISSUE TITLE
Every keystroke causes new tmp file to be created

### ISSUE THREAD

**Issue by pornel** [jhasse/sublime-rust#52]
As I type I can see new temp files appearing in Sublime's sidebar:

![screen shot 2015-05-21 at 21 34 35](https://cloud.githubusercontent.com/assets/72159/7758386/3aae4a08-0001-11e5-8d24-c04a159a89e2.png)

The temp files contain copy of the currently edited file.

**Comment by jhasse** [comment]
Are you sure this is caused by sublime-rust?

**Comment by pornel** [comment]
Oops, I'm not :)

It happens only with .rs files, but I forgot I've got another plugin, which is the culprit.
